import {C} from './config.js';import {gaugeValue} from './gauge.js';import {Game} from './physics.js';import {Assets} from './assets.js';import {Renderer} from './render.js';import {Audio,storage} from './audio.js';
const $=id=>document.getElementById(id),assets=new Assets();await assets.load();const params=new URLSearchParams(location.search),g=new Game(Number(params.get('seed'))||20260908),renderer=new Renderer($('scene'),assets),audio=new Audio();
let best=storage.get('best',0),muted=storage.get('muted',false),shake=storage.get('shake',true),seen=storage.get('seen',false),last=0,acc=0,toastTime=0,resultShown=false,userPaused=false,hiddenPaused=false,orientationPaused=false;
const ui={time:0,run:0,kick:0,angle:45,power:.5,gauge:0,tipAt:0};
audio.muted=muted;renderer.shakeEnabled=shake;const fixedSeed=params.has('seed'),debug=params.has('debug');$('debug').hidden=!debug;
function preference(){audio.muted=muted;renderer.shakeEnabled=shake;$('mute').textContent=muted?'소리 꺼짐 ♩':'소리 켜짐 ♪';$('shake').textContent='화면 흔들림 '+(shake?'켜짐':'꺼짐');}preference();
function toast(text,seconds=1.8){if(!text)return;$('toast').textContent=text;toastTime=seconds;$('toast').style.opacity=1;}
function syncPanels(){const state=g.state;$('menu').hidden=state!=='menu';$('hud').hidden=state==='menu';$('launch').hidden=!['angle','power'].includes(state);$('controls').hidden=!['power','run','angle','kick','flight'].includes(state);$('pause-panel').hidden=!userPaused;$('result').hidden=state!=='result';$('menu-best').textContent=Math.floor(best)+' m';}
function setLaunchPanel(mode){const power=mode==='power';$('choose').textContent=power?'위력 결정':'각도 결정';$('launch-gauge').classList.toggle('power-gauge',power);}
function clearRun(){toastTime=0;$('toast').style.opacity=0;resultShown=false;ui.run=0;ui.kick=0;ui.gauge=0;ui.tipAt=0;userPaused=false;renderer.trail=[];renderer.particles=[];renderer.fxBursts=[];renderer.camera={x:-115,y:0,zoom:1};}
function fresh(){g.reset(fixedSeed?g.seed:crypto.getRandomValues(new Uint32Array(1))[0]);clearRun();g.state='power';setLaunchPanel('power');syncPause();syncPanels();}
function menu(){g.reset();clearRun();syncPause();syncPanels();}
function choose(){if(g.paused)return;if(g.state==='power'){g.state='run';ui.run=0;syncPanels();}else if(g.state==='angle'){g.state='kick';ui.kick=0;syncPanels();}}
function syncPause(){g.paused=userPaused||hiddenPaused||orientationPaused;g.pendingJump=false;acc=0;last=performance.now();syncPanels();}
function bind(id,fn){$(id).addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(!e.isPrimary)return;audio.unlock();fn(e);});}
bind('start',fresh);bind('retry',fresh);bind('choose',choose);bind('result-main',menu);bind('pause-main',menu);bind('pause',()=>{userPaused=true;syncPause();});bind('resume',()=>{userPaused=false;syncPause();});bind('empower',()=>g.empower());bind('mute',()=>{muted=!muted;storage.set('muted',muted);preference();});bind('shake',()=>{shake=!shake;storage.set('shake',shake);preference();});bind('help-open',()=>{$('help').hidden=false;});bind('help-close',()=>{$('help').hidden=true;});
$('scene').addEventListener('pointerdown',e=>{e.preventDefault();if(!e.isPrimary)return;audio.unlock();if(['angle','power'].includes(g.state))choose();else if(g.state==='flight'&&!g.paused)g.pendingJump=true;});
document.addEventListener('visibilitychange',()=>{hiddenPaused=document.hidden;if(hiddenPaused&&g.state!=='menu')userPaused=true;syncPause();});
function orientation(){const bounds=$('game').getBoundingClientRect();C.height=Math.round(bounds.height*390/bounds.width);$('scene').height=C.height;orientationPaused=matchMedia('(orientation:landscape) and (max-height:600px)').matches;syncPause();}window.addEventListener('resize',orientation);orientation();
const guides={cat:['일반: 점프하며 양손으로 높은 토스','강화: 잠시 지면 반동 감속 없이 소폭 가속'],maid:['일반: 품에 안겨 즉시 정지','강화: 아주 강하게 전방 재발사'],koko:['일반: 전방 위쪽으로 발차기','강화: 불꽃 펀치 연타'],inori:['일반: 다음 충돌 효과 1회 무효','강화: 어퍼컷 + 다음 충돌 강화'],ppung:['일반: 이동 속도 크게 감소','강화: 약간 감속 + 잠시 1회 부활']};
for(const [key,lines]of Object.entries(guides)){const row=document.createElement('div'),pic=document.createElement('canvas'),text=document.createElement('div');row.className='guide';pic.width=64;pic.height=96;assets.draw(pic.getContext('2d'),key,'idle',0,32,92);text.innerHTML='<b>'+C.characters[key].name+'</b><p>'+lines.join('<br>')+'</p>';row.append(pic,text);$('character-guide').append(row);}
function hud(){const distance=Math.floor(g.maxX*C.metersPerPixel),speed=Math.round(Math.hypot(g.p.vx,g.p.vy)*.36),canJump=g.canJump();$('distance').innerHTML=distance+' <em>m</em>';$('best').textContent='BEST '+Math.floor(best)+' m';$('speed').textContent=speed;$('jump-touch').hidden=!canJump;$('jump-count').textContent='남은 점프 '+g.jumps+'회';$('charge-value').textContent=Math.floor(g.charge)+'%';$('charge-fill').style.width=g.charge+'%';$('empower').disabled=g.charge<100||g.inori==='next'||g.manual>0||g.state!=='flight'||g.paused||g.lock>0;$('empower').textContent=g.inori==='next'?'✦ 예약됨':g.manual>0?'✦ '+g.manual.toFixed(1)+'s':'✦ 강화';let buffs=[];if(g.inori)buffs.push(g.inori==='null'?'◌ 다음 충돌 무효':'✧ 다음 충돌 강화');if(g.manual>0)buffs.push('✦ 강화 '+g.manual.toFixed(1)+'초');if(g.bounceBuff>0)buffs.push('↟ 바운스UP '+g.bounceBuff.toFixed(1)+'초');if(g.revive>0)buffs.push('♡ 부활 '+g.revive.toFixed(1)+'초');$('buffs').innerHTML=buffs.map(b=>'<span>'+b+'</span>').join('');const next=g.field.items.filter(e=>e.x>g.p.x+35).sort((a,b)=>a.x-b.x)[0];$('preview').textContent=next?'앞으로 '+Math.round((next.x-g.p.x)*.1)+'m · '+C.characters[next.kind].name+' →':'';if(debug)$('debug').querySelector('pre').textContent=JSON.stringify({state:g.state,vx:g.p.vx.toFixed(1),vy:g.p.vy.toFixed(1),ground:g.p.ground,contact:[...g.contacts],jumps:g.jumps,buff:g.inori,revive:g.revive.toFixed(2),manual:g.manual.toFixed(2),bounceBuff:g.bounceBuff.toFixed(2),hold:g.hitstop.toFixed(2),seed:g.seed},null,1);}
function result(){if(resultShown)return;resultShown=true;const d=Math.floor(g.maxX*C.metersPerPixel),record=d>best;if(record){best=d;storage.set('best',best);audio.play('record');for(let i=0;i<4;i++)renderer.effect({type:'strong',x:g.p.x+i*30,y:g.p.y-120,text:''});}$('record-label').textContent=record?'✦ NEW RECORD ✦':'NICE FLIGHT!';$('result-title').textContent=record?'새로운 최고 기록!':'잘 날았다, 앵알이!';$('final-distance').innerHTML=d+'<small>m</small>';$('result-reason').textContent=g.reason;$('stats').innerHTML=[['최고 기록',best+' m'],['최대 속도',Math.round(g.stats.maxSpeed*.36)+' km/h'],['캐릭터 충돌',g.stats.contacts+'회'],['공중 점프',g.stats.jumps+' / 3'],['부활',g.stats.revives+'회'],['비행 시간',g.time.toFixed(1)+'초']].map(([a,b])=>'<div>'+a+'<b>'+b+'</b></div>').join('');syncPanels();}
function frame(now){const elapsed=Math.min(.25,Math.max(0,(now-last)/1000));last=now;const dt=g.paused?0:elapsed;if(!g.paused){ui.time+=dt;ui.gauge+=dt;if(['angle','power'].includes(g.state)){const value=gaugeValue(g.state,ui.gauge);$('needle').style.left=value*98+'%';if(g.state==='angle')ui.angle=C.angleMin+value*(C.angleMax-C.angleMin);else ui.power=value;$('gauge-value').textContent=g.state==='angle'?Math.round(ui.angle)+'°':Math.round(ui.power*100)+'%';}if(g.state==='run'){ui.run+=dt;if(ui.run>=.62){g.state='angle';ui.gauge=0;setLaunchPanel('angle');syncPanels();}}if(g.state==='kick'){ui.kick+=dt;if(ui.kick>=.52){g.launch(ui.angle,ui.power);syncPanels();if(!seen){ui.tipAt=4;toast('떨어질 때 화면을 눌러 점프! 한 판에 3번',4);seen=true;storage.set('seen',true);}}}acc+=dt;while(acc>=C.step){g.update(C.step);acc-=C.step;}if(ui.tipAt&&g.time>=ui.tipAt){toast('게이지가 차면 강화 버튼!',3);ui.tipAt=0;}for(const e of g.events.splice(0)){renderer.effect(e);audio.play(e.type);if(e.text)toast(e.text);}toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;}renderer.draw(g,dt,ui);hud();if(g.state==='result'){result();const cc=$('celebration').getContext('2d');cc.clearRect(0,0,96,112);cc.imageSmoothingEnabled=false;assets.draw(cc,'uaeng','celebrate',ui.time%1.5,48,108,1);}requestAnimationFrame(frame);}
bind('spawn',()=>g.field.add($('spawn-kind').value,g.p.x+250));bind('fill',()=>{g.charge=100;});
if(debug)window.__game={g,ui,assets,renderer,fresh,menu,choose,step:n=>{for(let i=0;i<n;i++)g.update(C.step);},setPause:v=>{userPaused=v;syncPause();}};
syncPanels();requestAnimationFrame(frame);
