import {C} from './config.js';
export class Renderer{
 constructor(canvas,assets){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.assets=assets;this.camera={x:-115,y:0,zoom:1};this.particles=[];this.fxBursts=[];this.trail=[];this.shake=0;this.shakeEnabled=true;this.birdAnim='flap';this.birdAt=0;}
 effect(e){this.fxBursts.push({...e,age:0});if(e.type!=='bounce')this.birdAnim=['jump','revive','stop'].includes(e.type)?e.type:'hit';this.birdAt=0;this.shake=e.type==='strong'?7:3;const color={null:'#6ce3ee',inori:'#82b8f5',ppung:'#ac7dcd',strong:'#ffd159',revive:'#c99cfa',jump:'#fffced'}[e.type]||'#ffe9a1';for(let i=0;i<(e.type==='strong'?26:12);i++)this.particles.push({x:e.x,y:e.y,vx:Math.cos(i*2.4)*120,vy:Math.sin(i*2.4)*130-40,life:.6+i%3*.12,max:1,color,size:2+i%3});}
 draw(g,dt,ui){let ctx=this.ctx;ctx.imageSmoothingEnabled=false;const W=C.width,H=C.height;ctx.clearRect(0,0,W,H);const flight=g.state==='flight'||g.state==='result';this.birdAt+=dt;if(flight){const heightRatio=Math.min(1,Math.max(0,-g.p.y-C.body.bird.ry)/C.camera.heightRange);const target=Math.max(.46,Math.max(.54,1-Math.max(0,g.p.vx-520)/3300)+C.camera.lowZoom*(1-heightRatio)-C.camera.heightZoom*heightRatio);this.camera.zoom+=(target-this.camera.zoom)*Math.min(1,dt*4);this.camera.x+=(g.p.x-112/this.camera.zoom-this.camera.x)*Math.min(1,dt*9);this.camera.y+=(Math.min(0,g.p.y+245)-this.camera.y)*Math.min(1,dt*3);}else{this.camera.x=-95;this.camera.y=0;this.camera.zoom=1.12;}
 const zoom=this.camera.zoom,ground=H*.77-this.camera.y*zoom;
 this.background(ctx,W,H,ground,this.camera.x,ui.time);
 ctx.save();if(this.shakeEnabled&&this.shake>0){ctx.translate(Math.round(Math.sin(ui.time*71)*this.shake),Math.round(Math.cos(ui.time*91)*this.shake*.5));}this.shake=Math.max(0,this.shake-dt*50);
 const sx=x=>Math.round((x-this.camera.x)*zoom),sy=y=>Math.round(ground+y*zoom);
 if(flight){if(g.time<.6)this.assets.draw(ctx,'uaeng','finish',g.time,sx(-50),ground,1);for(const e of g.field.items){const x=sx(e.x);if(x<-100||x>W+100)continue;let pose=e.anim,time=e.animTime;if(pose==='fireWindup'&&time>.48){pose='firePunch';time-=.48;}if(pose==='throw'){const a=this.assets.manifest?.sheets.maid.animations.throw;const duration=a?a.frames.length/a.fps:.5;if(time>=duration){pose='idle';time-=duration;}}if(time>1.1&&pose!=='catch')pose='idle';ctx.fillStyle='#4b745440';ctx.fillRect(x-22,ground-3,45,6);this.assets.draw(ctx,e.kind,pose,time,x,ground,zoom);ctx.fillStyle='#fffced';ctx.fillRect(x-26,ground+13,52,18);ctx.fillStyle=C.characters[e.kind].color;ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.fillText(C.characters[e.kind].name,x,ground+26);}
 if(g.p.vx>650){ctx.fillStyle='#fff9';for(let i=0;i<9;i++){const y=(i*71+30)%H,x=((i*93-ui.time*g.p.vx*.5)%440+440)%440;ctx.fillRect(x,y,Math.min(46,g.p.vx*.022),2);}}
 if(g.caught)this.trail=[];if(dt>0&&!g.caught){this.trail.push({x:g.p.x,y:g.p.y});if(this.trail.length>7)this.trail.shift();}for(let i=0;i<this.trail.length;i++){ctx.globalAlpha=i/this.trail.length*.16;this.assets.draw(ctx,'bird','flap',ui.time,sx(this.trail[i].x),sy(this.trail[i].y)+18,1);}ctx.globalAlpha=1;
 const bx=sx(g.p.x),by=sy(g.p.y);if(g.inori||g.manual>0||g.revive>0){const c=g.inori==='null'?'#4bbbe0':g.inori==='next'||g.manual>0?'#dfa539':'#b081d3';this.ring(ctx,bx,by,c,31,ui.time);if(g.revive>0)this.ring(ctx,bx,by,'#a56ce0',39,-ui.time);}
 if(g.bounceBuff>0)this.ring(ctx,bx,by,'#ffb845',43,ui.time*2);
 if(!g.caught){let pose=this.birdAt<.4?this.birdAnim:g.state==='result'?'stop':g.p.ground?'bounce':g.p.vy>9?'fall':g.p.vx>800?'spin':'flap';ctx.save();ctx.translate(bx,by);if(pose==='hit'||pose==='bounce')ctx.scale(1.15,.85);if(!g.p.ground&&pose==='flap')ctx.rotate(Math.sin(ui.time*6)*.22);this.assets.draw(ctx,'bird',pose,this.birdAt,0,18,1);ctx.restore();if(by<150){ctx.fillStyle='#fffde8';ctx.fillRect(74,143,110,27);ctx.fillStyle='#4e6370';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText('↑ 앵알이 '+Math.round(-g.p.y*.1)+'m',129,161);}}
 if(g.cinematic?.strong){ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(0,0,W,H);const e=g.cinematic,ex=sx(e.x);let action=e.pose,actionTime=e.elapsed;if(action==='fireWindup'&&actionTime>.5){action='firePunch';actionTime-=.5;}if(action==='throw'){const a=this.assets.manifest?.sheets.maid.animations.throw;const duration=a?a.frames.length/a.fps:.5;if(actionTime>=duration){action='idle';actionTime-=duration;}}this.assets.draw(ctx,e.kind,action,actionTime,ex,ground,zoom);this.assets.draw(ctx,'bird','hit',e.elapsed,bx,by+18,1);}
 if(g.guard){const q=Math.min(1,g.guard.elapsed/g.guard.duration),tx=sx(g.guard.targetX),gx=tx-155*(1-q),gy=ground;if(q<1){for(let i=3;i>=1;i--){ctx.globalAlpha=.28/i;this.assets.draw(ctx,'inori','prepare',g.guard.elapsed,gx-i*22,gy,1.05);}ctx.globalAlpha=1;}this.assets.draw(ctx,'inori',q<1?'prepare':'idle',g.guard.elapsed,gx,gy,1.05);this.ring(ctx,tx,ground-55,'#75d7f2',24,g.guard.elapsed*12);}
 for(const e of g.field.items){if(!e.effectLabel||e.animTime>1.8)continue;const x=sx(e.x);if(x<-80||x>W+80)continue;ctx.save();ctx.globalAlpha=Math.min(1,(1.8-e.animTime)/.4);ctx.font='bold 16px Arial';ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='#fffdf0';ctx.fillStyle='#503358';const y=ground-104*zoom-Math.min(12,e.animTime*8);ctx.strokeText(e.effectLabel,x,y);ctx.fillText(e.effectLabel,x,y);ctx.restore();}
 }else if(g.state==='menu'){const gy=H*.58;ctx.fillStyle='#4b74542b';ctx.fillRect(107,gy,172,8);this.assets.draw(ctx,'uaeng','idle',ui.time,155,gy,1.55);this.assets.draw(ctx,'bird','flap',ui.time,255,gy,1.65);this.ring(ctx,257,gy-45,'#ffffff',48,ui.time*.5);}
 else{let pose='idle',x=82,animTime=ui.time,scale=1.18;if(g.state==='run'){pose='run';x=20+ui.run*115;animTime=ui.run;}else if(g.state==='angle'){pose='prepare';x=91;animTime=.3;}else if(g.state==='kick'){pose='kick';x=91;animTime=ui.kick;}this.assets.draw(ctx,'uaeng',pose,animTime,x,ground,scale);this.assets.draw(ctx,'bird','idle',ui.time,159,ground,1.12);if(g.state==='angle'){const a=ui.angle*Math.PI/180;ctx.fillStyle='#e57369';for(let i=0;i<7;i++)ctx.fillRect(162+Math.cos(a)*i*12,ground-26-Math.sin(a)*i*12,5,5);}}
 for(const fx of this.fxBursts){fx.age+=dt;this.assets.drawEffect(ctx,fx.type,fx.age,sx(fx.x),sy(fx.y));}this.fxBursts=this.fxBursts.filter(fx=>fx.age<.5);
 for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(sx(p.x),sy(p.y),p.size,p.size);}ctx.globalAlpha=1;this.particles=this.particles.filter(p=>p.life>0);ctx.restore();
 }
 ring(ctx,x,y,color,r,t){ctx.fillStyle=color;for(let i=0;i<16;i++){const a=i*Math.PI/8+t;ctx.fillRect(Math.round(x+Math.cos(a)*r),Math.round(y+Math.sin(a)*r*.7),4,4);}}
 background(ctx,w,h,ground,camera,time){ctx.fillStyle='#d8f1e4';ctx.fillRect(0,0,w,h);ctx.fillStyle='#edf7da';ctx.fillRect(0,h*.3,w,h*.7);ctx.fillStyle='#f9edb1';ctx.fillRect(288,172,46,46);ctx.fillStyle='#fff8d1';ctx.fillRect(296,166,30,58);
 const cloud=(x,y,s)=>{ctx.fillStyle='#ffffffb8';ctx.fillRect(x,y,70*s,13*s);ctx.fillRect(x+12*s,y-10*s,38*s,12*s);ctx.fillRect(x+23*s,y-17*s,20*s,12*s);};for(let i=0;i<5;i++){const x=((i*157-camera*.06)%650+650)%650-100;cloud(x,130+i%3*88,.75+i%2*.4);}
 const hillY=Math.min(h-100,Math.max(420,ground-80));ctx.fillStyle='#bedcb7';for(let i=-1;i<6;i++){const x=i*110-((camera*.12)%110);ctx.fillRect(x,hillY+30,110,h);ctx.fillRect(x+12,hillY+8,85,35);ctx.fillRect(x+27,hillY-8,55,28);}ctx.fillStyle='#92bd94';for(let i=-1;i<6;i++){const x=i*95-((camera*.25)%95);ctx.fillRect(x,hillY+95,95,h);ctx.fillRect(x+18,hillY+66,65,36);ctx.fillRect(x+30,hillY+51,40,30);}
 if(ground<h+40){ctx.fillStyle='#71ae7b';ctx.fillRect(0,ground,w,h-ground);ctx.fillStyle='#a6cd84';ctx.fillRect(0,ground,390,9);ctx.fillStyle='#d1dd9b';ctx.fillRect(0,ground+9,390,5);ctx.fillStyle='#bad39a';ctx.fillRect(0,ground+14,390,h);for(let i=-1;i<19;i++){const x=i*27-((camera)%27);ctx.fillStyle=i%3?'#8cb582':'#f7e8b0';ctx.fillRect(x,ground+27+i%4*17,4,3);ctx.fillStyle='#61936e';ctx.fillRect(x+7,ground-4,3,6);}}}
}

